<a href="https://colab.research.google.com/github/aminfazy/FPD_IITP_21/blob/main/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
* Details @ [Numpy web page](https://numpy.org/) and @ [Github page](https://cs231n.github.io/python-numpy-tutorial/) 

* Numpy is the core library for scientific computing in Python.

* It provides a high-performance multidimensional array object, and tools for working with these arrays.

* Various routines are provided for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. 


In [1]:
import numpy as np

In [21]:
na = [[1,2],[2,2],[2,3]]
len(na)

3

In [26]:
pa = np.array([[[1,1],[5,3],[3,4]],[[2,6],[4,8],[2,3]],[[2,2],[5,4],[3,6]]])
pa.shape

(3, 3, 2)

In [30]:
ca = pa.reshape(-1)
ca

array([1, 1, 5, 3, 3, 4, 2, 6, 4, 8, 2, 3, 2, 2, 5, 4, 3, 6])

In [34]:
a=np.array([[2,3,4,5],[5,4,6,3],[7,3,6,1],[7,5,3,9]])
b=np.array([[3,4,6,7],[8,4,2,6],[8,5,9,1],[6,2,8,4]])
c=a*b
c

array([[ 6, 12, 24, 35],
       [40, 16, 12, 18],
       [56, 15, 54,  1],
       [42, 10, 24, 36]])

In [32]:
# define arrays are to be used for the various operations in following cells
a=np.array([[2,3,4,5],[5,4,6,3],[7,3,6,1],[7,5,3,9]])
b=np.array([[3,4,6,7],[8,4,2,6],[8,5,9,1],[6,2,8,4]])

c=np.array([[2,3,4,5],[7,3,6,1],[7,5,3,9]])
d=np.array([[3,4,6,7],[8,4,2,6],[8,5,9,1]])

e=np.array([[4,6,7],[8,2,6],[8,5,1],[2,8,4]])

In [35]:
# matrix multiplication

out = np.matmul(a,b) # np.matnul and np.dot are same for 2 D arrays
print(out)

[[ 92  50  94  56]
 [113  72 116  77]
 [ 99  72 110  77]
 [139  81 151 118]]


In [36]:
# transpose operation

print(a)
out = np.transpose(a)
print(out)

[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
[[2 5 7 7]
 [3 4 3 5]
 [4 6 6 3]
 [5 3 1 9]]


In [38]:
# Power of Matrix

print(a)
out = np.linalg.matrix_power(a,2)
print(out)

[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
[[ 82  55  65  68]
 [ 93  64  89  70]
 [ 78  56  85  59]
 [123  95 103 134]]


In [39]:
# Determinant of a Matrix

print(a)
out = np.linalg.det(a)
print(out)

print(b)
out = np.linalg.det(b)
print(out)

[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
-153.0000000000001
[[3 4 6 7]
 [8 4 2 6]
 [8 5 9 1]
 [6 2 8 4]]
-1324.0000000000002


In [40]:
# Norm of matrix

print(a)
out = np.linalg.norm(a)
print(out)

[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
19.974984355438178


In [41]:
# Trace of Matrix

print(a)
out = np.trace(a)
print(out)

print(e)
out = np.trace(e)
print(out)


[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
21
[[4 6 7]
 [8 2 6]
 [8 5 1]
 [2 8 4]]
7


In [42]:
# Inverse of a Square Matrix

print(a)
out = np.linalg.inv(a)
print(out)


[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
[[-0.05882353 -0.26143791  0.25490196  0.09150327]
 [-0.94117647  1.48366013 -0.92156863  0.13071895]
 [ 0.47058824 -0.35294118  0.29411765 -0.17647059]
 [ 0.41176471 -0.50326797  0.21568627  0.02614379]]


In [43]:
# Inverse of a General Matrix (Pseudo-inverse)

print(e)
out = np.linalg.pinv(e)
print(out)



[[4 6 7]
 [8 2 6]
 [8 5 1]
 [2 8 4]]
[[-0.03678043  0.05846663  0.09680761 -0.04753609]
 [ 0.00558298 -0.08714837  0.05772672  0.10652066]
 [ 0.09682106  0.08383894 -0.12901403 -0.01294176]]


In [44]:
# Rank of Matrix

print(a)
out = np.linalg.matrix_rank(a)
print(out)

print(e)
out = np.linalg.matrix_rank(e)
print(out)

[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
4
[[4 6 7]
 [8 2 6]
 [8 5 1]
 [2 8 4]]
3


In [45]:
# Singular Value Decompostion

print(c.shape)
print(c)
u, sigma, v = np.linalg.svd(c)
print(u.shape, sigma.shape, v.shape)
print(u)
print(sigma)
print(v)

(4, 4)
[[ 6 12 24 35]
 [40 16 12 18]
 [56 15 54  1]
 [42 10 24 36]]
(4, 4) (4,) (4, 4)
[[-0.29712454  0.64556777 -0.61599272 -0.33987088]
 [-0.41334018  0.08158724  0.63962104 -0.64294505]
 [-0.6771765  -0.64608    -0.35214113  0.00304147]
 [-0.53131807  0.39895665  0.29569327  0.68636739]]
[109.62150403  40.83721134  23.98292436   7.69852993]
[[-0.7165893  -0.2339848  -0.56020246 -0.34340077]
 [-0.30088745  0.08204712 -0.21648605  0.92513178]
 [ 0.60827026  0.02155032 -0.79337094  0.01026772]
 [ 0.16116392 -0.96853238  0.09934557  0.16156015]]


In [46]:
# Eigen Value Decomposition

print(a)
L, V = np.linalg.eig(a) # L eigenvalues and corresponding right eigen vectors
print(L.shape, V.shape)
print(L)
print(V)

[[2 3 4 5]
 [5 4 6 3]
 [7 3 6 1]
 [7 5 3 9]]
(4,) (4, 4)
[18.11422957  5.28437632 -2.94191576  0.54330987]
[[-0.39774337  0.11320089 -0.73671045  0.16985445]
 [-0.45704748 -0.38031366 -0.11251286 -0.90639932]
 [-0.39979025 -0.54503096  0.57711869  0.22244604]
 [-0.68780489  0.73857182  0.33396495  0.3163977 ]]
